apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-myweb
spec:
  replicas : 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      name: myweb
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: foozly/dyma-k8s-p1:v0.0.4
          ports:
            - containerPort: 80